### PR TITLE
Update to Swift 6.0.2

### PR DESCRIPTION
**Pull request by colemancda**
Builds Swift 6.0.2 for Buildroot and adds support for StringProcessing and Observable modules.

### CODE REVIEW

**Comment by xtremekforever** [comment]
The only thing that seems to be missing here is building [swift-testing](https://github.com/colemancda/swift-armv7/blob/main/build-swift-testing.sh) for buildroot. This is new in Swift 6.0 and later. Do you plan on including swift-testing as well?

**Comment by colemancda** [comment]
@xtremekforever It would be trivial to add, but TBH I don't see the utility ATM. All the Apple maintained Swift packages can be built with cmake (especially the ones shipped with Darwin like System and CryptoKit), so the standard Buildroot cmake infrastructure can easily build them. I think Debian is a better platform for development and testing. My Buildroot port is focused on release builds and production deployment.

**Comment by xtremekforever** [comment]
@colemancda by that logic then you don't need XCTest in there either right? But that's fine, I see that it's not needed unless you want to run test cases on the target board itself.

The files all look solid, I just don't know how to build this since it's been over a decade since I built Buildroot. But looks good to me!

**Comment by colemancda** [comment]
I want to remove all the test related stuff, XCTest and hello-swift is just for quick testing in a qemu-static chroot.

**Pull request merged**
